In [3]:
import numpy as np

In [6]:
x = np.array([1,2,3,4])
type(x)

numpy.ndarray

In [7]:
x.dtype

dtype('int32')

In [12]:
y = np.array([1,2,3,4], dtype=np.int64) #явно указываем тип данных

In [13]:
y.dtype

dtype('int64')

In [14]:
y.shape #размерность массива по всем осям

(4,)

In [18]:
m = np.array([ [2,3,4], [5,6,7] ])   

In [19]:
m  #матрица

array([[2, 3, 4],
       [5, 6, 7]])

In [20]:
m.shape #количество строк и столбцов

(2, 3)

In [21]:
np.ones(5) #создание массива с помощью встроенной функции

array([1., 1., 1., 1., 1.])

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [27]:
np.random.random([2,3])

array([[0.87600673, 0.00588233, 0.05319973],
       [0.80705105, 0.61253011, 0.00296239]])

работа с значениями массивов

In [30]:
y[0]

1

In [31]:
y2 = np.array([ [1, 3, 4, 4], [2, 3, 4, 56] ])  

In [32]:
y2

array([[ 1,  3,  4,  4],
       [ 2,  3,  4, 56]])

если же мы хотим вытащить какой-то элемент, находящийся на допустим первой строке и в третьем столбце, нам необходимо задать индексы и сразу же по двум осям, то есть сначала мы первым аргументом в квадратных скобках указываем индекс по оси X, а как второй аргумент указываем индекс спроси Y, и в данном случае у нас возвращается число

In [42]:
y2[1,3]

56

In [45]:
y2[:, :3]  #все строки до 3 столбца

array([[1, 3, 4],
       [2, 3, 4]])

In [46]:
#Допустим у нас есть некоторый массив, мы хотим найти все значения, превышающие либо меньше какого-то либо заданного числа

y2 > 2 

array([[False,  True,  True,  True],
       [False,  True,  True,  True]])

In [51]:
#и затем, для того, чтобы вытащить нужное нам значение, мы эту маску передаем как индекс наш массив, 
#в результате этого возвращается уже массив значений удостоверяющих условию
y2[y2 > 2]   #КВАДРАТНЫЕ СКОБКИ!!!!!!!

array([ 3,  4,  4,  3,  4, 56])

ОБРАБОТКА ДАННЫХ

In [52]:
b = np.array([ [1, 3, 4, 4, 5], [2, 3, 4, 56, 5] ])  

In [56]:
b

array([[ 1,  3,  4,  4,  5],
       [ 2,  3,  4, 56,  5]])

In [53]:
b.shape

(2, 5)

попробуем развернуть все значения хранящиеся в нашей матрице в одноименный массив

In [54]:
b.flatten()

array([ 1,  3,  4,  4,  5,  2,  3,  4, 56,  5])

In [55]:
b.T  #ТРАСНПОНИРОВАНИЕ МАТРИЦЫ

array([[ 1,  2],
       [ 3,  3],
       [ 4,  4],
       [ 4, 56],
       [ 5,  5]])

по другому ее создать, например, используя метод reshape, мы можем получить некоторый массив из десяти элементов. Для этого в методе reshape необходимо передать новые значения по двум осям X и Y, которые мы хотим увидеть. Важно отметить, что размер новой формы, он не должен по количеству элементов превышать размер нашей исходной матрицы, то есть если у нас в матрице было всего десять элементов, мы никак не можем задать форму, в которой будет, например,15 элементов, мы получим сразу же ошибку. 

In [64]:
b.reshape(10,1)

array([[ 1],
       [ 3],
       [ 4],
       [ 4],
       [ 5],
       [ 2],
       [ 3],
       [ 4],
       [56],
       [ 5]])

И также используя метод resize, можно поменять форму нашего исходного массива. Отличие resize от reshape заключается в том, что resize автоматически меняет исходный массив в то время как reshape просто изменяет ее форму

In [65]:
b.resize(10,1)

In [66]:
b

array([[ 1],
       [ 3],
       [ 4],
       [ 4],
       [ 5],
       [ 2],
       [ 3],
       [ 4],
       [56],
       [ 5]])

ОПЕРАЦИИ

In [67]:
v = np.array([9, 10])  
w = np.array([11, 12])


In [68]:
v + w

array([20, 22])

In [69]:
np.add(v, w)  #второй способ сложения

array([20, 22])

Мы видим, что результат тот же самый, и результатом является массив такого же размера, что исходные вектора, и стоит отметить, что данный вид операций подразумевает под собой поэлементное сложение, то есть мы складываем каждый элемент друг с другом.

In [70]:
v-w

array([-2, -2])

In [72]:
np.subtract(v,w)

array([-2, -2])

In [73]:
v * w

array([ 99, 120])

In [75]:
np.multiply(v,w)

array([ 99, 120])

для того, чтобы посчитать какое либо скалярное произведение между векторами либо умножить вектор на матрицу, нам необходимо воспользоваться другим методом. Он называется dot и на вход принимает два вектора, которые мы хотим приумножить. Допустим, давайте посмотрим скалярное произведение двух векторов, результатом которого уже будет не некоторый массив, а уже какое-то конкретное число.

In [76]:
np.dot(v,w)

219

array([55, 60])